spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/compute?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
